name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure minio/mc
      run: "docker run --rm \\\n-v $(pwd):/data \\\n minio/mc -C /data alias set --insecure myminio https://minio.sanjairocky.in \\\n ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    - name: upload static files
      run: |
        docker run --rm \
        -v "$(pwd)":/data \
        minio/mc -C /data mirror --overwrite \
        --insecure --remove /data/public/ \
        myminio/${{ github.event.repository.name }}.site


